export const UPDATE_GAME = "UPDATE_GAME";
export const UPDATE_GAMES = "UPDATE_GAMES";
export const UPDATE_GENRES = "UPDATE_GENRES";
export const UPDATE_SEARCHED_GAMES = "UPDATE_SEARCHED_GAMES";

export const UPDATE_NAVBAR = "UPDATE_NAVBAR";
